<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Acc_branch_group_model extends CI_Model
{

    public $table = 'acc_branch_group';
    public $id = 'branch_group_guid';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('a.concept_guid, a.branch_group_guid, a.isactive, a.group_name, a.created_at,
            a.created_by, a.updated_at, a.updated_by, b.concept_name');
        $this->datatables->from('acc_branch_group a');
        //add this line for join
        $this->datatables->join('acc_concept b', 'a.concept_guid = b.concept_guid');
        $this->datatables->add_column('action', anchor(site_url('acc_branch_group/read/$1'),'Read', 'class="btn btn-info btn-xs "')."  ".anchor(site_url('acc_branch_group/update/$1'),'Update', 'class="btn btn-success btn-xs"')."  ".anchor(site_url('acc_branch_group/delete/$1'),'<i class="fa fa-trash fa-lg" style="color:red"></i>','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'branch_group_guid');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->select('acc_concept.concept_name, acc_branch_group.*');
        $this->db->join('acc_concept', 'acc_concept.concept_guid = acc_branch_group.concept_guid');
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->select('acc_concept.concept_name, acc_branch_group.*');
        $this->db->where($this->id, $id);
        $this->db->join('acc_concept', 'acc_concept.concept_guid = acc_branch_group.concept_guid');
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('branch_group_guid', $q);
	$this->db->or_like('concept_guid', $q);
	$this->db->or_like('isactive', $q);
	$this->db->or_like('group_name', $q);
	$this->db->or_like('created_at', $q);
	$this->db->or_like('created_by', $q);
	$this->db->or_like('updated_at', $q);
	$this->db->or_like('updated_by', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('branch_group_guid', $q);
	$this->db->or_like('concept_guid', $q);
	$this->db->or_like('isactive', $q);
	$this->db->or_like('group_name', $q);
	$this->db->or_like('created_at', $q);
	$this->db->or_like('created_by', $q);
	$this->db->or_like('updated_at', $q);
	$this->db->or_like('updated_by', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Acc_branch_group_model.php */
/* Location: ./application/models/Acc_branch_group_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-12-23 13:03:44 */
/* http://harviacode.com */