<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Acc_master_setup_model extends CI_Model
{

    function __construct()
    {
        parent::__construct();
    }

    // insert data
    function insert_data($table, $data)
    {
        $this->db->insert($table, $data);
    }

    // update data
    function update_data($table,$col_guid, $guid, $data)
    {
        $this->db->where($col_guid, $guid);
        $this->db->update($table, $data);
    }

    // delete data
    function delete_data($table, $col_guid, $guid)
    {
        $this->db->where($col_guid, $guid);
        $this->db->delete($table);
    }

    // delete data
    function delete_user_group($table, $col_guid, $guid)
    {
        $sql = $this->db->query("DELETE a.*, b.*, c.* FROM acc_user_group a INNER JOIN acc_user_module b ON a.`acc_user_group_guid` = b.`acc_user_group_guid` INNER JOIN acc_user c ON a.`acc_user_group_guid` = c.`acc_user_group_guid` WHERE a.`acc_user_group_guid` = '$guid' ");
        $query = $this->db->query($sql);
        return $query;   
    }

}

/* End of file Acc_model.php */
/* Location: ./application/models/Acc_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-12-23 13:03:44 */
/* http://harviacode.com */