<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Acc_concept_model extends CI_Model
{

    public $table = 'acc_concept';
    public $id = 'concept_guid';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->select('acc.acc_name, acc_concept.*');
        $this->db->where($this->id, $id);
        $this->db->join('acc', 'acc.acc_guid = acc_concept.acc_guid');
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('concept_guid', $q);
	$this->db->or_like('acc_guid', $q);
	$this->db->or_like('isactive', $q);
	$this->db->or_like('concept_name', $q);
	$this->db->or_like('created_at', $q);
	$this->db->or_like('created_by', $q);
	$this->db->or_like('updated_at', $q);
	$this->db->or_like('updated_by', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('concept_guid', $q);
	$this->db->or_like('acc_guid', $q);
	$this->db->or_like('isactive', $q);
	$this->db->or_like('concept_name', $q);
	$this->db->or_like('created_at', $q);
	$this->db->or_like('created_by', $q);
	$this->db->or_like('updated_at', $q);
	$this->db->or_like('updated_by', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Acc_concept_model.php */
/* Location: ./application/models/Acc_concept_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-12-23 13:03:45 */
/* http://harviacode.com */